//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#ifndef BRIDGING_HEADER_H
#define BRIDGING_HEADER_H

#include "J2ObjC_header.h"
#import <sqlite3.h>

#include "JavaObject.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"

#include "java/com/softwareverde/util/WebRequest.h"
#include "java/com/softwareverde/util/Json.h"

#include "java/com/softwareverde/utopia/Session.h"
#include "java/com/softwareverde/utopia/database/Database.h"
#include "java/com/softwareverde/utopia/database/KeyValueStore.h"
#include "java/com/softwareverde/utopia/database/UtopiaDatabaseV1.h"
#include "java/com/softwareverde/utopia/Vibrator.h"
#include "java/com/softwareverde/utopia/intelsync/IntelSync.h"
#include "java/com/softwareverde/utopia/intelsync/IntelSyncFactory.h"
#include "java/com/softwareverde/utopia/NotificationMaker.h"

#include "java/com/softwareverde/utopia/Province.h"
#include "java/com/softwareverde/utopia/Kingdom.h"


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/softwareverde/utopia/ActiveSpell.h"
#include "com/softwareverde/utopia/Settings.h"
#include "com/softwareverde/utopia/Building.h"
#include "com/softwareverde/utopia/ChatCredentials.h"
#include "com/softwareverde/utopia/Chatroom.h"
#include "com/softwareverde/utopia/DraftRate.h"
#include "com/softwareverde/utopia/Dragon.h"
#include "com/softwareverde/utopia/Forum.h"
#include "com/softwareverde/utopia/Kingdom.h"
#include "com/softwareverde/utopia/NotificationMaker.h"
#include "com/softwareverde/utopia/PrivateMessage.h"
#include "com/softwareverde/utopia/Province.h"
#include "com/softwareverde/utopia/ProvinceCredentials.h"
#include "com/softwareverde/utopia/ProvinceTagUtil.h"
#include "com/softwareverde/utopia/Science.h"
#include "com/softwareverde/utopia/Session.h"
#include "com/softwareverde/utopia/Spell.h"
#include "com/softwareverde/utopia/ThieveryOperation.h"
#include "com/softwareverde/utopia/TrainArmyData.h"
#include "com/softwareverde/util/Util.h"
#include "com/softwareverde/utopia/UtopiaUtil.h"
#include "com/softwareverde/utopia/Vibrator.h"
#include "com/softwareverde/utopia/bundle/ActiveSpellsBundle.h"
#include "com/softwareverde/utopia/bundle/ArmyOffenseBundle.h"
#include "com/softwareverde/utopia/bundle/AttackBundle.h"
#include "com/softwareverde/utopia/bundle/AttackDragonInfoBundle.h"
#include "com/softwareverde/utopia/bundle/AvailableSpellsBundle.h"
#include "com/softwareverde/utopia/bundle/AvailableThieveryOperationBundle.h"
#include "com/softwareverde/utopia/bundle/AvailableThieveryOperationsBundle.h"
#include "com/softwareverde/utopia/bundle/BuildCostBundle.h"
#include "com/softwareverde/utopia/bundle/BuildingsBundle.h"
#include "com/softwareverde/utopia/bundle/Bundle.h"
#include "com/softwareverde/utopia/bundle/BundleFactory.h"
#include "com/softwareverde/utopia/bundle/ChatroomBundle.h"
#include "com/softwareverde/utopia/bundle/DraftRateBundle.h"
#include "com/softwareverde/utopia/bundle/ExplorationCostsBundle.h"
#include "com/softwareverde/utopia/bundle/ForumTopicPostsBundle.h"
#include "com/softwareverde/utopia/bundle/ForumTopicsBundle.h"
#include "com/softwareverde/utopia/bundle/FundDragonInfoBundle.h"
#include "com/softwareverde/utopia/bundle/InfiltrateThievesBundle.h"
#include "com/softwareverde/utopia/bundle/KingdomBundle.h"
#include "com/softwareverde/utopia/bundle/KingdomIntelBundle.h"
#include "com/softwareverde/utopia/bundle/MilitaryBundle.h"
#include "com/softwareverde/utopia/bundle/MilitarySettingsBundle.h"
#include "com/softwareverde/utopia/bundle/NewsBundle.h"
#include "com/softwareverde/utopia/bundle/NewspaperBundle.h"
#include "com/softwareverde/utopia/bundle/PrivateMessageBundle.h"
#include "com/softwareverde/utopia/bundle/PrivateMessagesBundle.h"
#include "com/softwareverde/utopia/bundle/ProvinceIdBundle.h"
#include "com/softwareverde/utopia/bundle/ProvinceIdsBundle.h"
#include "com/softwareverde/utopia/bundle/ProvinceIntelBundle.h"
#include "com/softwareverde/utopia/bundle/ScienceBundle.h"
#include "com/softwareverde/utopia/bundle/SpellResultBundle.h"
#include "com/softwareverde/utopia/bundle/StateCouncilBundle.h"
#include "com/softwareverde/utopia/bundle/ThieveryOperationBundle.h"
#include "com/softwareverde/utopia/bundle/ThroneBundle.h"
#include "com/softwareverde/utopia/bundle/TradeSettingsBundle.h"
#include "com/softwareverde/utopia/bundle/WarRoomBundle.h"
#include "com/softwareverde/utopia/database/KeyValueStore.h"
#include "com/softwareverde/utopia/database/UtopiaDatabase.h"
#include "com/softwareverde/utopia/intelsync/IntelSync.h"
#include "com/softwareverde/utopia/intelsync/IntelSyncFactory.h"
#include "com/softwareverde/utopia/intelsync/UpoopuUtil.h"
#include "com/softwareverde/utopia/intelsync/UmunkUtil.h"
#include "com/softwareverde/utopia/intelsync/StingerUtil.h"
#include "com/softwareverde/utopia/intelsync/VerdeIntelUtil.h"
#include "com/softwareverde/utopia/news/NewsEvent.h"
#include "com/softwareverde/utopia/util/Base64Util.h"
#include "com/softwareverde/utopia/util/JavaScriptExecutor.h"
#include "com/softwareverde/utopia/util/BuildVersion.h"
#include "com/softwareverde/utopia/parser/HtmlParser.h"
#include "com/softwareverde/utopia/parser/JsoupHtmlParser.h"
#include "com/softwareverde/utopia/parser/UtopiaParser.h"
#include "java/io/PrintStream.h"
#include "java/lang/Boolean.h"
#include "java/lang/Double.h"
#include "java/lang/Exception.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/Math.h"
#include "java/lang/Runnable.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/System.h"
#include "java/lang/Thread.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"
#include "java/util/HashMap.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

#endif